### PR TITLE
Delete last line on datasets/simple-join/output.jsonl

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
[issue#128](https://github.com/mlcommons/croissant/issues/128)

Hi [marcenacp](https://github.com/marcenacp),
last line on datasets/simple-join/output.jsonl deleted, please check it out

### CODE REVIEW

**Comment by viktoriussuwandi** [comment]
recheck

**Comment by marcenacp** [comment]
Hi @viktoriussuwandi, thanks for the PR!

You changed the test. Now:

1. You would need to change the code that takes care of the join: https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join.py
2. You could add unit tests in the corresponding test: https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join_test.py

**Review by marcenacp — CHANGES_REQUESTED** [review]
See: https://github.com/mlcommons/croissant/pull/129#issuecomment-1635801956

**Comment by viktoriussuwandi** [comment]
> Hi @viktoriussuwandi, thanks for the PR!
> 
> You changed the test. Now:
> 
> 1. You would need to change the code that takes care of the join: https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join.py
> 2. You could add unit tests in the corresponding test: https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join_test.py

Hi [marcenacp](https://github.com/marcenacp),

Actually, I love to contribute on your repo, but I have no idea how to do these requests, 
would you please let me know step by step ?

Appreciate your guidance

**Comment by marcenacp** [comment]
Hi @viktoriussuwandi, sorry for this! Here are some more detailed steps:

1. Read how the repo is designed [in the README](https://github.com/mlcommons/croissant/tree/main/python/ml_croissant#design). In particular, this explains what "operations" are.
2. Read the description of the failing dataset: https://github.com/mlcommons/croissant/blob/main/datasets/simple-join/metadata.json. It joins two sets:
  - a list of publications
  - with a list of authors.
4. So the problem comes from the [`Join` operation](https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join.py). After investigation, I think you would have to invert `source` and `references` to fix the issue: https://github.com/mlcommons/croissant/blob/main/datasets/simple-join/metadata.json#L99-L100
5. If you can, add a unit test with an example of a similar join between two pd.DataFrames in the corresponding test: https://github.com/mlcommons/croissant/blob/main/python/ml_croissant/ml_croissant/_src/operation_graph/operations/join_test.py
6. Update your code until the command `pytest .` (running pytest tests) is green.

Please, tell me if it's not clear. Thanks a lot!

**Comment by marcenacp** [comment]
@viktoriussuwandi The problem was tricky... I submitted https://github.com/mlcommons/croissant/pull/146, which better documents how to do joins.

I'll close this PR for now. Thanks again!

**Pull request closed without merging**
