### PR TITLE
Add Sphinx to support readthedocs

### PR DESCRIPTION
**Pull request by marcenacp**
@nathanw-mlc I'd like to setup readthedocs. Have you already done it for other mlcommons repos? Is it possible to set up the OAuth binding as explained in https://docs.readthedocs.io/en/stable/tutorial/index.html?

### CODE REVIEW

**Comment by marcenacp** [comment]
> So far we've used [Material for MKDocs](https://squidfunk.github.io/mkdocs-material/).

I see it's used by major Python libraries like FastAPI or Pydantic. It looks great! Thanks for the link. What should I do to set it up for ml_croissant?

**Comment by nathanw-mlc** [comment]
> What should I do to set it up for ml_croissant?

I'm bringing @sergey-serebryakov into this conversation, as he works with Material for MkDocs for MLCube and has set it up for another project of his.

**Comment by sergey-serebryakov** [comment]
Hi @marcenacp. I have limited knowledge about how to use Sphinx for generating and hosting documentation, and can not be of great help here I am afraid. But I have used [mkdocs](https://www.mkdocs.org/) approach to turn (sometimes specially formatted) markdown documents into documentation web sites hosted with GitHub pages. 
Nathan provided several examples, for instance, [MLCube](https://mlcommons.github.io/mlcube/). We use GitHub workflows that automatically trigger on certain events and rebuild documentation. It's not as powerful as Sphinx, but I believe much easier to use, and have basic capabilities to generate [API](https://hewlettpackard.github.io/cmf/api/public/cmf/) and [CLI](https://mlcommons.github.io/mlcube/getting-started/cli/) docs automatically.
If you think this approach works for `croissant` project, I can help setting up initial documentation and GitHub workflows.

**Comment by marcenacp** [comment]
@sergey-serebryakov Thank you for getting back to me. I'm willing to use mkdocs. I can mirror [`mlcube/docs/`](https://github.com/mlcommons/mlcube/tree/master/docs) and [`mlcube/.github/workflows/docs-site.yml`](https://github.com/mlcommons/mlcube/blob/master/.github/workflows/docs-site.yml). I'll ping you if I encounter any problem!

In the meantime, I created https://github.com/mlcommons/croissant/issues/174 and will close this PR.

**Pull request closed without merging**
